using Microsoft.EntityFrameworkCore;
using SWZZPI_HFT_2023241.Models;

namespace SWZZPI_HFT_2023241.Repository
{
    public class LolDBContext : DbContext
    {
        public DbSet<Abilities> Abilities { get; set; }
        public DbSet<Champions> Champions { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public LolDBContext()
        {
            this.Database.EnsureCreated();
        }
        protected override void OnConfiguring(DbContextOptionsBuilder dbContextOptionsBuilder)
        {
            if (!dbContextOptionsBuilder.IsConfigured)
            {
                dbContextOptionsBuilder
                    .UseLazyLoadingProxies()
                    .UseInMemoryDatabase("Lol");
            }
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Champions>(champion => champion
                                           .HasOne(champion => champion.Region)
                                           .WithMany(region => region.Champions)
                                           .HasForeignKey(champion => champion.RegionsId)
                                           .OnDelete(DeleteBehavior.Cascade));
            modelBuilder.Entity<Abilities>(ability => ability
                                           .HasOne(ability => ability.Champion)
                                           .WithMany(champion => champion.Abilities)
                                           .HasForeignKey(ability => ability.ChampionId)
                                           .OnDelete(DeleteBehavior.Cascade));
            modelBuilder.Entity<Regions>().HasData(new Regions[]
                {
                    new Regions("1*Shurima*South*Unknown*Divine Empire*Desert"),
                    new Regions("2*Noxus*North*Medium*Expansionist Empire*Steppes"),
                    new Regions("3*Ionia*North-East*Low*Regona Provinces*Magical"),
                    new Regions("4*Demacia*West*Medium*Feudal Monarchy*Countryside"),
                    new Regions("5*Freljord*North*Low*Tribal Matriarchy*Tundra"),
                    new Regions("6*Piltover*Middle*High*Aristocratic Oligarchy*Metropolis"),
                    new Regions("7*Zaun*Middle*High*Industrial Oligarchy*Urbanized"),
                    new Regions("8*BandleCity*South*Unknown*None*Unknown"),
                    new Regions("9*Bilgewater*East*Medium*Gang Syndicates*Archipelago"),
                    new Regions("10*ShadowIsles*South-East*Low*None*Archipelago"),
                    new Regions("11*The Void*South*Unknown*None*Unknown"),
                    new Regions("12*Ixtal*South*Alchemical*Magical Autocracy*Rainforest"),
                    new Regions("13*Targon*South-West*Low*Tribal Theocracy*Mountains"),
                    new Regions("14*Runeterra*The World*All*None*All")
                });
            modelBuilder.Entity<Champions>().HasData(new Champions[]
            {
                new Champions("1*Aatrox*Male*Darkin*Top, Middle*2013*14"),
                new Champions("2*Ahri*Female*Vastayan*Middle*2011*3"),
                new Champions("3*Akali*Female*Ninja*Top, Middle*2010*3"),
                new Champions("4*Akshan*Male*Human*Top, Middle, Bottom*2021*1"),
                new Champions("5*Alistar*Male*Minotaur*Support*2009*14"),
                new Champions("6*Amumu*Male*Yordle*Jungle, Support*2009*1"),
                new Champions("7*Anivia*Female*God*Middle, Support*2009*5"),
                new Champions("8*Annie*Female*Magicborn*Middle, Support*2009*14"),
                new Champions("9*Aphelios*Male*Human*Bottom*2019*13"),
                new Champions("10*Ashe*Female*Human*Bottom*2009*5"),
                new Champions("11*Aurelion Sol*Male*Celestial*Middle*2016*14"),
                new Champions("12*Azir*Male*God*Middle*2014*1"),
                new Champions("13*Bard*Male*Celestial*Support*2015*14"),
                new Champions("14*Bel'Veth*Female*Void being*Jungle*2022*11"),
                new Champions("15*Blitzcrank*Other*Robot*Support*2009*7"),
                new Champions("16*Brand*Male*Magically Altered Human*Jungle, Middle, Support*2011*14"),
                new Champions("17*Braum*Male*Human*Support*2014*5"),
                new Champions("18*Briar*Male*Demon*Jungle*2023*2"),
                new Champions("19*Caitlyn*Female*Human*Bottom*2011*6"),
                new Champions("20*Camille*Female*Cyborg*Top, Middle*2016*6"),
                new Champions("21*Cassiopeia*Female*Human*Top, Middle, Support*2010*2"),
                new Champions("22*Cho'Gath*Male*Void being*Top, Jungle, Middle, Support*2009*11"),
                new Champions("23*Corki*Male*Yordle*Middle, Bottom*2009*8"),
                new Champions("24*Darius*Male*Human*Top*2012*2"),
                new Champions("25*Diana*Female*Aspect*Jungle, Middle*2012*13"),
                new Champions("26*Dr. Mundo*Male*Chemically Altered Human*Top, Jungle*2009*7"),
                new Champions("27*Draven*Male*Human*Nottom*2012*2"),
                new Champions("28*Ekko*Male*Human*Jungle, Middle*2015*7"),
                new Champions("29*Elise*Female*Human*Jungle*2012*10"),
                new Champions("30*Evelynn*Female*Demon*Jungle*2009*11"),
                new Champions("31*Ezreal*Male*Human*Bottom*2010*6"),
                new Champions("32*Fiddlesticks*Other*Demon*Jungle, Support*2009*14"),
                new Champions("33*Fiora*Female*Human*Top*2012*4"),
                new Champions("34*Fizz*Male*Yordle*Middle*2011*14"),
                new Champions("35*Galio*Male*Golem*Middle, Support*2010*4"),
                new Champions("36*Gangplank*Male*Human*Top, Middle*2009*9"),
                new Champions("37*Garen*Male*Human*Top, Middle*2010*4"),
                new Champions("38*Gnar*Male*Yordle*Top*2014*5"),
                new Champions("39*Gragas*Male*Human*Top, Jungle, Support*2010*5"),
                new Champions("40*Graves*Male*Human*Jungle*2011*9"),
                new Champions("41*Gwen*Female*Human*Top, Jungle*2021*10"),
                new Champions("42*Hecarim*Male*Undead*Jungle*2012*10"),
                new Champions("43*Heimerdinger*Male*Yordle*Top, Middle, Bottom*2009*6"),
                new Champions("44*Illaoi*Female*Human*Top*2015*9"),
                new Champions("45*Irelia*Female*Human*Top, Middle*2010*3"),
                new Champions("46*Ivern*Male*Magically Altered Human*Jungle, Support*2016*3"),
                new Champions("47*Janna*Female*God*Support*2009*7"),
                new Champions("48*Jarvan IV*Male*Human*Jungle*2011*4"),
                new Champions("49*Jax*Male*Unknown*Top, Jungle*2009*14"),
                new Champions("50*Jayce*Male*Human*Top, Middle*2012*6"),
                new Champions("51*Jhin*Male*Human*Bottom*2016*3"),
                new Champions("52*Jinx*Female*Human*Bottom*2013*7"),
                new Champions("53*Kai'Sa*Female*Void being*Bottom*2018*11"),
                new Champions("54*Kalista*Female*Undead*Top, Bottom*2014*10"),
                new Champions("55*Karma*Female*Human*Top, Support*2011*3"),
                new Champions("56*Karthus*Male*Undead*Jungle, Middle*2009*10"),
                new Champions("57*Kassadin*Male*Void being*Middle*2009*11"),
                new Champions("58*Katarina*Female*Human*Middle*2009*2"),
                new Champions("59*Kayle*Female*Aspect*Top, Middle*2009*4"),
                new Champions("60*Kayn*Male*Darkin, Human*Jungle*2017*3"),
                new Champions("61*Kennen*Male*Yordle*Top, Middle*2010*3"),
                new Champions("62*Kha'Zix*Male*Void being*Jungle*2012*11"),
                new Champions("63*Kindred*Other*God*Jungle*2015*14"),
                new Champions("64*Kled*Male*Yordle*Top, Middle*2016*2"),
                new Champions("65*Kog'Maw*Male*Void being*Middle, Bottom*2010*11"),
                new Champions("66*K'Sante*Male*Human*Top*2022*1"),
                new Champions("67*LeBlanc*Female*Human*Middle, Support*2010*2"),
                new Champions("68*Lee Sin*Male*Human*Jungle*2011*3"),
                new Champions("69*Leona*Female*Aspect*Support*2011*13"),
                new Champions("70*Lillia*Female*Spirit*Top, Jungle*2020*3"),
                new Champions("71*Lissandra*Female*Human*Middle, Support*2013*5"),
                new Champions("72*Lucian*Male*Human*Middle, Bottom*2013*14"),
                new Champions("73*Lulu*Female*Yordle*Support*2012*8"),
                new Champions("74*Lux*Female*Human*Middle, Support*2010*4"),
                new Champions("75*Malphite*Male*Golem*Top, Middle, Bottom*2009*12"),
                new Champions("76*Malzahar*Male*Human, Void being*Top, Middle*2010*11"),
                new Champions("77*Maokai*Male*Spirit*Top, Support*2011*10"),
                new Champions("78*Master Yi*Male*Human*Jungle*2009*3"),
                new Champions("79*Milio*Male*Human*Support*2023*12"),
                new Champions("80*Miss Fortune*Female*Human*Bottom*2010*9"),
                new Champions("81*Mordekaiser*Male*Revenant*Top, Jungle*2010*2"),
                new Champions("82*Morgana*Female*Aspect*Jungle, Support*2009*4"),
                new Champions("83*Naafiri*Male*Darkin*Middle*2023*1"),
                new Champions("84*Nami*Female*Vastayan*Support*2012*14"),
                new Champions("85*Nasus*Male*God*Top, Middle*2009*1"),
                new Champions("86*Nautilus*Male*Revenant*Support*2012*9"),
                new Champions("87*Neeko*Female*Vastayan*Middle, Support*2018*12"),
                new Champions("88*Nidalee*Female*Human*Jungle, Support*2009*12"),
                new Champions("89*Nilah*Female*Human*Bottom*2022*9"),
                new Champions("90*Nocturne*Male*Demon*Jungle*2011*14"),
                new Champions("91*Nunu & Willump*Male*Human, Yeti*Jungle, Middle*2009*5"),
                new Champions("92*Olaf*Male*Human*Top, Jungle*2010*5"),
                new Champions("93*Orianna*Female*Golem*Middle*2011*6"),
                new Champions("94*Ornn*Male*God*Top*2017*5"),
                new Champions("95*Pantheon*Male*Aspect*Top, Jungle, Middle, Support*2010*13"),
                new Champions("96*Poppy*Female*Yordle*Top, Support*2010*4"),
                new Champions("97*Pyke*Male*Revenant*Support*2018*9"),
                new Champions("98*Qiyana*Female*Human*Jungle, Middle*2019*12"),
                new Champions("99*Quinn*Female*Human*Top, Middle*2013*4"),
                new Champions("100*Rakan*Male*Vastayan*Support*2017*3"),
                new Champions("101*Rammus*Male*Jungle*2009*1"),
                new Champions("102*Rek'Sai*Female*Void being*Jungle*2014*11"),
                new Champions("103*Rell*Female*Human*Jungle, Support*2020*2"),
                new Champions("104*Renata Glasc*Human*Female*Support*2022*7"),
                new Champions("105*Renekton*Male*God*Top, Middle*2011*1"),
                new Champions("106*Rengar*Male*Vastayan*Top, Jungle*2012*12"),
                new Champions("107*Riven*Female*Human*Top, Middle*2011*2"),
                new Champions("108*Rumble*Male*Yordle*Top, Jungle, Middle*2011*8"),
                new Champions("109*Ryze*Male*Human*Top, Middle*2009*14"),
                new Champions("110*Samira*Female*Human*Bottom*2020*2"),
                new Champions("111*Sejuani*Female*Human*Jungle*2012*5"),
                new Champions("112*Senna*Female*Human, Undead*Bottom, Support*2019*14"),
                new Champions("113*Seraphine*Female*Human*Middle, Bottom, Support*2020*6"),
                new Champions("114*Sett*Male*Vastayan*Top, Middle, Support*2020*3"),
                new Champions("115*Shaco*Male*Spirit*Jungle*2009*14"),
                new Champions("116*Shen*Male*Human*Top*2010*3"),
                new Champions("117*Shyvana*Female*Dragon*Top, Jungle*2011*4"),
                new Champions("118*Singed*Male*Human*Top, Middle*2009*7"),
                new Champions("119*Sion*Male*Revenant*Top, Middle*2009*2"),
                new Champions("120*Sivir*Female*Human*Bottom*2009*1"),
                new Champions("121*Skarner*Male*Brackern*Top, Jungle*2011*1"),
                new Champions("122*Sona*Female*Magicborn*Support*2010*4"),
                new Champions("123*Soraka*Female*Celestial*Support*2009*13"),
                new Champions("124*Swain*Male*Human*Top, Middle, Support*2010*2"),
                new Champions("125*Sylas*Male*Human*Top, Middle*2019*4"),
                new Champions("126*Syndra*Female*Human*Middle*2012*3"),
                new Champions("127*Tahm Kench*Male*Demon*Top*2015*14"),
                new Champions("128*Taliyah*Female*Human*Jungle*2016*1"),
                new Champions("129*Talon*Male*Human*Jungle, Middle*2011*2"),
                new Champions("130*Taric*Male*Aspect*Support*2009*13"),
                new Champions("131*Teemo*Male*Yordle*Top, Jungle, Support*2009*8"),
                new Champions("132*Thresh*Male*Undead*Support*2013*10"),
                new Champions("133*Tristana*Female*Yordle*Middle, Bottom*2009*8"),
                new Champions("134*Trundle*Male*Troll*Top, Jungle*2010*5"),
                new Champions("135*Tryndamere*Male*Human*Top, Middle*2009*5"),
                new Champions("136*Twisted Fate*Male*Human*Middle*2009*9"),
                new Champions("137*Twitch*Male*Chemically Altered Rat*Bottom*2009*7"),
                new Champions("138*Udyr*Male*Human*Top, Jungle*2009*5"),
                new Champions("139*Urgot*Male*Cyborg*Top*2010*7"),
                new Champions("140*Varus*Male*Darkin, Human*Middle, Bottom*2012*3"),
                new Champions("141*Vayne*Female*Human*Top, Bottom*2011*4"),
                new Champions("142*Veigar*Male*Yordle*Middle, Bottom, Support*2009*8"),
                new Champions("143*Vel'Koz*Male*Void being*Middle, Support*2014*11"),
                new Champions("144*Vex*Female*Yordle*Middle*2021*10"),
                new Champions("145*Vi*Female*Human*Jungle*2012*6"),
                new Champions("146*Viego*Male*Undead*Jungle*2021*10"),
                new Champions("147*Viktor*Male*Human*Middle*2011*7"),
                new Champions("148*Vladimir*Male*Magically Altered Human*Top, Middle*2010*2"),
                new Champions("149*Volibear*Male*God*Top, Jungle*2011*5"),
                new Champions("150*Warwick*Male*Chemically Altered Human*Top, Jungle*2009*7"),
                new Champions("151*Wukong*Male*Vastayan*Top*2011*3"),
                new Champions("152*Xayah*Female*Vastayan*Bottom*2017*3"),
                new Champions("153*Xerath*Male*God*Middle, Support*2011*1"),
                new Champions("154*Xin Zhao*Male*Human*Top, Jungle, Middle*2017*4"),
                new Champions("155*Yasuo*Male*Human*Top, Middle, Bottom*2013*3"),
                new Champions("156*Yone*Male*Human*Top, Middle*2020*3"),
                new Champions("157*Yorick*Male*Human*Top, Middle*2011*10"),
                new Champions("158*Yuumi*Female*Cat*Support*2019*8"),
                new Champions("159*Zac*Male*Golem*Jungle*2013*7"),
                new Champions("160*Zed*Male*Human*Jungle, Middle*2012*3"),
                new Champions("161*Zeri*Female*Human*Bottom*2022*7"),
                new Champions("162*Ziggs*Male*Yordle*Middle, Bottom*2012*7"),
                new Champions("163*Zilean*Male*Human*Support*2009*14"),
                new Champions("164*Zoe*Female*Aspect*Middle, Support*2017*13"),
                new Champions("165*Zyra*Female*Unknown*Support*2012*12"),
            });
            modelBuilder.Entity<Abilities>().HasData(new Abilities[]
                {
                    new Abilities("1*90 Caliber Net*E*19"),
                    new Abilities("2*A Harmless Scarecrow*P*32"),
                    new Abilities("3*Above & Below*W*14"),
                    new Abilities("4*Abscond / Abduct*E*125"),
                    new Abilities("5*Absolute Zero*R*91"),
                    new Abilities("6*Absolution*P*112"),
                    new Abilities("7*Abyssal Drive*W*127"),
                    new Abilities("8*Ace in the Hole*R*19"),
                    new Abilities("9*Adaptive Defenses*P*20"),
                    new Abilities("10*Aegis Assault*E*95"),
                    new Abilities("11*All Out*R*66"),
                    new Abilities("12*Allure*W*30"),
                    new Abilities("13*Alpha Strike*Q*78"),
                    new Abilities("14*Ambush*Q*137"),
                    new Abilities("15*An Acquired Taste*P*127"),
                    new Abilities("16*Apotheosis*R*89"),
                    new Abilities("17*Apprehend*E*24"),
                    new Abilities("18*Aqua Prison*Q*84"),
                    new Abilities("19*Arcane Mastery*P*109"),
                    new Abilities("20*Arcane Shift*E*31"),
                    new Abilities("21*Arcanopulse*Q*153"),
                    new Abilities("22*Arctic Assault*Q*111"),
                    new Abilities("23*Ardent Blaze*W*72"),
                    new Abilities("24*Aria of Perseverance*W*122"),
                    new Abilities("25*Arise!*W*12"),
                    new Abilities("26*Aspect of The Cougar*R*88"),
                    new Abilities("27*Assassin's Mark*P*3"),
                    new Abilities("28*Assassin's Path*E*129"),
                    new Abilities("29*Astral Flight*W*11"),
                    new Abilities("30*Astral Infusion*W*123"),
                    new Abilities("31*Audacious Charge*E*154"),
                    new Abilities("32*Audacity*E*98"),
                    new Abilities("33*Avengerang*Q*4"),
                    new Abilities("34*Backstab*P*115"),
                    new Abilities("35*Bailout*W*104"),
                    new Abilities("36*Baleful Strike*Q*142"),
                    new Abilities("37*Bandage Toss*Q*6"),
                    new Abilities("38*Barrel Roll*Q*39"),
                    new Abilities("39*Bastion*W*130"),
                    new Abilities("40*Battle Dance*E*100"),
                    new Abilities("41*Battle Fury*P*135"),
                    new Abilities("42*Battle Roar*W*106"),
                    new Abilities("43*Beartrap on a Rope*Q*64"),
                    new Abilities("44*Beat Drop*E*113"),
                    new Abilities("45*Behind Enemy Lines*R*99"),
                    new Abilities("46*Bellows Breath*W*94"),
                    new Abilities("47*Berserker Rage*P*92"),
                    new Abilities("48*Biggest Snowball Ever!*W*91"),
                    new Abilities("49*Binding Eclipse*Q*9"),
                    new Abilities("50*Bio-Arcane Barrage*W*65"),
                    new Abilities("51*Black Shield*E*82"),
                    new Abilities("52*Blade of the Exile*R*107"),
                    new Abilities("53*Blade of the Ruined King*Q*146"),
                    new Abilities("54*Blade Whirl*W*110"),
                    new Abilities("55*Blade's End*P*129"),
                    new Abilities("56*Blade's Reach*W*60"),
                    new Abilities("57*Bladecaller*E*152"),
                    new Abilities("58*Bladesurge*Q*45"),
                    new Abilities("59*Bladework*E*33"),
                    new Abilities("60*Blast Shield*P*145"),
                    new Abilities("61*Blaze*P*16"),
                    new Abilities("62*Blazing Stampede*E*138"),
                    new Abilities("63*Blighted Quiver*W*140"),
                    new Abilities("64*Blinding Assault*Q*99"),
                    new Abilities("65*Blinding Dart*Q*131"),
                    new Abilities("66*Blood Frenzy*W*18"),
                    new Abilities("67*Blood Hunt*W*150"),
                    new Abilities("68*Blood Rush*W*27"),
                    new Abilities("69*Bloodlust*Q*135"),
                    new Abilities("70*Blooming Blows*Q*70"),
                    new Abilities("71*Blooming Burst*Q*87"),
                    new Abilities("72*Blunt Force Trauma*E*26"),
                    new Abilities("73*Body Slam*E*39"),
                    new Abilities("74*Bola Strike*E*106"),
                    new Abilities("75*Bone Skewer*Q*97"),
                    new Abilities("76*Boomerang Blade*Q*120"),
                    new Abilities("77*Boomerang Throw / Boulder Toss*Q*38"),
                    new Abilities("78*Bouncing Blades*Q*58"),
                    new Abilities("79*Bouncing Bomb*Q*162"),
                    new Abilities("80*Bountiful Harvest*W*32"),
                    new Abilities("81*Bramble Smash*Q*77"),
                    new Abilities("82*Bravado*P*130"),
                    new Abilities("83*Break the Mold*P*103"),
                    new Abilities("84*Breath of Life*R*79"),
                    new Abilities("85*Breath of Light*Q*11"),
                    new Abilities("86*Bridge Between*P*138"),
                    new Abilities("87*Broken Wings*Q*107"),
                    new Abilities("88*Brushmaker*W*46"),
                    new Abilities("89*Bullet Time*R*80"),
                    new Abilities("90*Burnout*W*117"),
                    new Abilities("91*Burrow / Unburrow*W*102"),
                    new Abilities("92*Burst Fire*Q*161"),
                    new Abilities("93*Bushwhack / Pounce*W*88"),
                    new Abilities("94*Buster Shot*R*133"),
                    new Abilities("95*Calibrum, the Sniper Rifle*P*9"),
                    new Abilities("96*Call of the Forge God*R*94"),
                    new Abilities("97*Call of the Freljord*P*91"),
                    new Abilities("98*Call of the Void*Q*76"),
                    new Abilities("99*Cannon Barrage*R*36"),
                    new Abilities("100*Captive Audience*E*51"),
                    new Abilities("101*Caretaker's Shrine*W*13"),
                    new Abilities("102*Carnivore*P*22"),
                    new Abilities("103*Cataclysm*R*48"),
                    new Abilities("104*Caustic Spittle*Q*65"),
                    new Abilities("105*Cease & Desist*R*145"),
                    new Abilities("106*Celestial Blessing*W*59"),
                    new Abilities("107*Cell Division*P*159"),
                    new Abilities("108*Certain Death*R*18"),
                    new Abilities("109*CH-2 Electron Storm Grenade*E*43"),
                    new Abilities("110*CH-3X Lightning Grenade*E*43"),
                    new Abilities("111*Chaaaaaaaarge!!!*R*64"),
                    new Abilities("112*Chain Lash*Q*125"),
                    new Abilities("113*Chain of Corruption*R*140"),
                    new Abilities("114*Chaos Storm*R*147"),
                    new Abilities("115*Charm*E*2"),
                    new Abilities("116*Chilling Scream*E*18"),
                    new Abilities("117*Chomp*Q*134"),
                    new Abilities("118*Chronobreak*R*28"),
                    new Abilities("119*Chronoshift*R*163"),
                    new Abilities("120*Chum the Waters*R*34"),
                    new Abilities("121*Clean Cuts*P*152"),
                    new Abilities("122*Clockwork Windup*P*93"),
                    new Abilities("123*Cocoon / Rappel*E*29"),
                    new Abilities("124*Collateral Damage*R*40"),
                    new Abilities("125*Colossal Smash*P*35"),
                    new Abilities("126*Comet Spear*Q*95"),
                    new Abilities("127*Comeuppance*R*4"),
                    new Abilities("128*Command: Attack*Q*93"),
                    new Abilities("129*Command: Dissonance*W*93"),
                    new Abilities("130*Command: Protect*E*93"),
                    new Abilities("131*Command: Shockwave*R*93"),
                    new Abilities("132*Concussive Blows*P*17"),
                    new Abilities("133*Condemn*E*141"),
                    new Abilities("134*Conflagration*E*16"),
                    new Abilities("135*Conquering Sands*Q*12"),
                    new Abilities("136*Consume*Q*91"),
                    new Abilities("137*Contaminate*E*137"),
                    new Abilities("138*Contempt for the Weak*P*160"),
                    new Abilities("139*Corrosive Charge*Q*139"),
                    new Abilities("140*Cosmic Binding*Q*13"),
                    new Abilities("141*Cosmic Creator*P*11"),
                    new Abilities("142*Cosmic Radiance*R*130"),
                    new Abilities("143*Counter Strike*E*49"),
                    new Abilities("144*Courage*W*37"),
                    new Abilities("145*Cozy Campfire*W*79"),
                    new Abilities("146*Crescendo*R*122"),
                    new Abilities("147*Crescendum, the Chakram*P*9"),
                    new Abilities("148*Crescent Guard*R*154"),
                    new Abilities("149*Crescent Strike*Q*25"),
                    new Abilities("150*Crimson Curse*P*18"),
                    new Abilities("151*Crimson Pact*P*148"),
                    new Abilities("152*Cripple*E*68"),
                    new Abilities("153*Crippling Strike*W*24"),
                    new Abilities("154*Crowstorm*R*32"),
                    new Abilities("155*Crunch*E*38"),
                    new Abilities("156*Crushing Blow*Q*151"),
                    new Abilities("157*Crystal Slash*Q*121"),
                    new Abilities("158*Crystal Spires*P*121"),
                    new Abilities("159*Crystalline Exoskeleton*W*121"),
                    new Abilities("160*Crystallize*W*7"),
                    new Abilities("161*Cull the Meek*Q*105"),
                    new Abilities("162*Curse of the Black Mist*E*112"),
                    new Abilities("163*Curse of the Sad Mummy*R*6"),
                    new Abilities("164*Cursed Touch*P*6"),
                    new Abilities("165*Curtain Call*R*51"),
                    new Abilities("166*Cyclone*R*151"),
                    new Abilities("167*Daisy!*R*46"),
                    new Abilities("168*Damnation*P*132"),
                    new Abilities("169*Dance of Arrows*Q*63"),
                    new Abilities("170*Dancing Grenade*Q*51"),
                    new Abilities("171*Daredevil Impulse*P*110"),
                    new Abilities("172*Dark Binding*Q*82"),
                    new Abilities("173*Dark Matter*W*142"),
                    new Abilities("174*Dark Passage*W*132"),
                    new Abilities("175*Dark Procession*W*157"),
                    new Abilities("176*Dark Sphere*Q*126"),
                    new Abilities("177*Darkin Daggers*Q*83"),
                    new Abilities("178*Darkness Rise*P*81"),
                    new Abilities("179*Dauntless Instinct*P*66"),
                    new Abilities("180*Dawning Shadow*R*112"),
                    new Abilities("181*Dazzle*E*130"),
                    new Abilities("182*Deadly Flourish*W*51"),
                    new Abilities("183*Deadly Plumage*W*152"),
                    new Abilities("184*Deadly Spines*Q*165"),
                    new Abilities("185*Deadly Venom*P*137"),
                    new Abilities("186*Death Defied*P*56"),
                    new Abilities("187*Death from Below*R*97"),
                    new Abilities("188*Death in Lavender*P*14"),
                    new Abilities("189*Death Lotus*R*58"),
                    new Abilities("190*Death Mark*R*160"),
                    new Abilities("191*Death Ray*E*147"),
                    new Abilities("192*Death Sentence*Q*132"),
                    new Abilities("193*Death Surge*P*119"),
                    new Abilities("194*Death's Grasp*E*81"),
                    new Abilities("195*Death's Hand*Q*124"),
                    new Abilities("196*Deathbringer Stance*P*1"),
                    new Abilities("197*Deceive*Q*115"),
                    new Abilities("198*Decimate*Q*24"),
                    new Abilities("199*Decimating Smash*Q*119"),
                    new Abilities("200*Decisive Strike*Q*37"),
                    new Abilities("201*Defensive Ball Curl*W*101"),
                    new Abilities("202*Defiance*E*55"),
                    new Abilities("203*Defiant Dance*W*45"),
                    new Abilities("204*Defile*E*56"),
                    new Abilities("205*Demacian Justice*R*37"),
                    new Abilities("206*Demacian Standard*E*48"),
                    new Abilities("207*Demon Shade*P*30"),
                    new Abilities("208*Demonflare*R*124"),
                    new Abilities("209*Demonic Ascension*R*124"),
                    new Abilities("210*Denting Blows*W*145"),
                    new Abilities("211*Depth Charge*R*86"),
                    new Abilities("212*Despair*W*6"),
                    new Abilities("213*Destiny*R*136"),
                    new Abilities("214*Determination*P*154"),
                    new Abilities("215*Devastating Charge*E*42"),
                    new Abilities("216*Devour*R*127"),
                    new Abilities("217*Dirty Fighting*P*4"),
                    new Abilities("218*Disdain*E*139"),
                    new Abilities("219*Disintegrate*Q*8"),
                    new Abilities("220*Distortion*W*67"),
                    new Abilities("221*Divine Ascent*P*59"),
                    new Abilities("222*Divine Judgment*R*59"),
                    new Abilities("223*Dominus*R*105"),
                    new Abilities("224*Doom'n Gloom*P*144"),
                    new Abilities("225*Double Daggers*Q*152"),
                    new Abilities("226*Double Strike*P*78"),
                    new Abilities("227*Double Up*Q*80"),
                    new Abilities("228*Dragon Strike*Q*48"),
                    new Abilities("229*Dragon's Descent*R*117"),
                    new Abilities("230*Dragon's Rage*R*68"),
                    new Abilities("231*Draw a Bead*P*133"),
                    new Abilities("232*Dream-Laden Bough*P*70"),
                    new Abilities("233*Dredge Line*Q*86"),
                    new Abilities("234*Drunken Rage*W*39"),
                    new Abilities("235*Duelist's Dance*P*33"),
                    new Abilities("236*Duskbringer*Q*90"),
                    new Abilities("237*Duskwave*Q*9"),
                    new Abilities("238*Ebb and Flow*W*84"),
                    new Abilities("239*Echoing Flames*P*139"),
                    new Abilities("240*Eclipse*W*69"),
                    new Abilities("241*Edge of Ixtal*Q*98"),
                    new Abilities("242*Elastic Slingshot*E*159"),
                    new Abilities("243*Electrical Surge*W*61"),
                    new Abilities("244*Electro-Harpoon*E*108"),
                    new Abilities("245*Emperor's Divide*R*12"),
                    new Abilities("246*Empower*W*49"),
                    new Abilities("247*Empowered Battle Roar*W*106"),
                    new Abilities("248*Empowered Bola Strike*E*106"),
                    new Abilities("249*Empowered Savagery*Q*106"),
                    new Abilities("250*Empowered Whiplash*E*30"),
                    new Abilities("251*Enchanted Crystal Arrow*R*10"),
                    new Abilities("252*Encore*R*113"),
                    new Abilities("253*End of the Line*Q*40"),
                    new Abilities("254*Endless Banquet*R*14"),
                    new Abilities("255*Equinox*E*123"),
                    new Abilities("256*Essence Flux*W*31"),
                    new Abilities("257*Essence Theft*P*2"),
                    new Abilities("258*Eternal Hunger*P*150"),
                    new Abilities("259*Ethereal Chains*E*67"),
                    new Abilities("260*Eulogy of the Isles*R*157"),
                    new Abilities("261*Event Horizon*E*142"),
                    new Abilities("262*Eviscerate*E*83"),
                    new Abilities("263*Explosive Cask*R*39"),
                    new Abilities("264*Explosive Charge*E*133"),
                    new Abilities("265*Eye of Destruction*W*153"),
                    new Abilities("266*Eye of the Storm*E*47"),
                    new Abilities("267*Facebreaker*E*114"),
                    new Abilities("268*Falling Star*R*11"),
                    new Abilities("269*Fate Sealed*R*156"),
                    new Abilities("270*Fate's Call*R*54"),
                    new Abilities("271*Fear Beyond Death*R*139"),
                    new Abilities("272*Feast*R*22"),
                    new Abilities("273*Featherstorm*R*152"),
                    new Abilities("274*Feline Friendship*P*158"),
                    new Abilities("275*Feral Scream*W*22"),
                    new Abilities("276*Ferromancy - Crash Down / Mount Up*W*103"),
                    new Abilities("277*Fey Feathers*P*100"),
                    new Abilities("278*Final Chapter*R*158"),
                    new Abilities("279*Final Hour*R*141"),
                    new Abilities("280*Final Spark*R*74"),
                    new Abilities("281*Fired Up!*P*79"),
                    new Abilities("282*Fishbones, the Rocket Launcher*Q*52"),
                    new Abilities("283*Five Point Strike*Q*3"),
                    new Abilities("284*Flair*Q*110"),
                    new Abilities("285*Flame Breath*E*117"),
                    new Abilities("286*Flame Chompers!*E*52"),
                    new Abilities("287*Flamespitter*Q*108"),
                    new Abilities("288*Flash Frost*Q*7"),
                    new Abilities("289*Flawless Duet*E*45"),
                    new Abilities("290*Flay*E*132"),
                    new Abilities("291*Fleet of Foot*P*120"),
                    new Abilities("292*Fling*E*118"),
                    new Abilities("293*Flurry*P*68"),
                    new Abilities("294*Focused Resolve*W*55"),
                    new Abilities("295*Footwork*E*66"),
                    new Abilities("296*Force of Will*W*126"),
                    new Abilities("297*Force Pulse*E*57"),
                    new Abilities("298*Formless Blade*Q*89"),
                    new Abilities("299*Fox-Fire*W*2"),
                    new Abilities("300*Fracture*E*121"),
                    new Abilities("301*Frenzied Maul*W*149"),
                    new Abilities("302*Frenzying Taunt*W*101"),
                    new Abilities("303*Friend of the Forest*P*46"),
                    new Abilities("304*Frost Shot*P*10"),
                    new Abilities("305*Frostbite*E*7"),
                    new Abilities("306*Frozen Domain*W*134"),
                    new Abilities("307*Frozen Tomb*R*71"),
                    new Abilities("308*Full Tilt*E*103"),
                    new Abilities("309*Furious Bite / Tunnel*E*102"),
                    new Abilities("310*Fury of the Dragonborn*P*117"),
                    new Abilities("311*Fury of the North*P*111"),
                    new Abilities("312*Fury of the Sands*R*85"),
                    new Abilities("313*Fury of the Xer'Sai*P*102"),
                    new Abilities("314*Garden of Thorns*P*165"),
                    new Abilities("315*Gathering Fire*P*55"),
                    new Abilities("316*Gatling Gun*E*23"),
                    new Abilities("317*Get Excited!*P*52"),
                    new Abilities("318*Ghostwater Dive*W*97"),
                    new Abilities("319*Gift of the Drowned Ones*P*97"),
                    new Abilities("320*Glacial Fissure*R*17"),
                    new Abilities("321*Glacial Path*E*71"),
                    new Abilities("322*Glacial Prison*R*111"),
                    new Abilities("323*Glacial Storm*R*7"),
                    new Abilities("324*Gleaming Quill*Q*100"),
                    new Abilities("325*Glitterlance*Q*73"),
                    new Abilities("326*Glorious Evolution*P*147"),
                    new Abilities("327*Glory in Death*P*119"),
                    new Abilities("328*GNAR!*R*38"),
                    new Abilities("329*Goes Where He Pleases*P*26"),
                    new Abilities("330*Going Rogue*W*4"),
                    new Abilities("331*Golden Aegis*W*48"),
                    new Abilities("332*Grand Challenge*R*33"),
                    new Abilities("333*Grand Entrance*W*100"),
                    new Abilities("334*Grand Starfall*R*95"),
                    new Abilities("335*Granite Shield*P*75"),
                    new Abilities("336*Grasping Roots*E*165"),
                    new Abilities("337*Gravitum, the Gravity Cannon*P*9"),
                    new Abilities("338*Gravity Field*W*147"),
                    new Abilities("339*Ground Slam*E*75"),
                    new Abilities("340*Guerrilla Warfare*P*131"),
                    new Abilities("341*H-28G Evolution Turret*Q*43"),
                    new Abilities("342*H-28Q Apex Turret*Q*43"),
                    new Abilities("343*Hail of Arrows*E*140"),
                    new Abilities("344*Hallowed Mist*W*41"),
                    new Abilities("345*Hallucinate*R*115"),
                    new Abilities("346*Hammer Shock*Q*96"),
                    new Abilities("347*Handshake*Q*104"),
                    new Abilities("348*Happy Hour*P*39"),
                    new Abilities("349*Harrier*P*99"),
                    new Abilities("350*Harrowed Path*E*146"),
                    new Abilities("351*Harsh lesson*W*44"),
                    new Abilities("352*Hate Spike*Q*30"),
                    new Abilities("353*Hawkshot*E*10"),
                    new Abilities("354*Haymaker*W*114"),
                    new Abilities("355*Head Rush*Q*18"),
                    new Abilities("356*Headbutt*W*5"),
                    new Abilities("357*Headshot*P*19"),
                    new Abilities("358*Heart Zapper*W*26"),
                    new Abilities("359*Heartbreaker*R*146"),
                    new Abilities("360*Heightened Senses*W*99"),
                    new Abilities("361*Help, Pix!*E*73"),
                    new Abilities("362*Hemoplague*R*148"),
                    new Abilities("363*Hemorrhage*P*24"),
                    new Abilities("364*Hero's Entrance*R*35"),
                    new Abilities("365*Heroic Charge*E*96"),
                    new Abilities("366*Heroic Swing*E*4"),
                    new Abilities("367*Hexplosive Minefield*E*162"),
                    new Abilities("368*Hextech Affinity*P*43"),
                    new Abilities("369*Hextech Capacitor*P*50"),
                    new Abilities("370*Hextech Micro-Rockets*W*43"),
                    new Abilities("371*Hextech Munitions*P*23"),
                    new Abilities("372*Hextech Rocket Swarm*W*43"),
                    new Abilities("373*Hextech Ultimatum*R*20"),
                    new Abilities("374*High Note*Q*113"),
                    new Abilities("375*Highlander*R*78"),
                    new Abilities("376*Hijack*R*125"),
                    new Abilities("377*Hookshot / Wall Dive*E*20"),
                    new Abilities("378*Hop / Crunch*E*38"),
                    new Abilities("379*Hostile Takeover*R*104"),
                    new Abilities("380*Hounds' Pursuit*W*83"),
                    new Abilities("381*Howling Gale*Q*47"),
                    new Abilities("382*Human Form / Spider Form*R*29"),
                    new Abilities("383*Hymn of Valor*Q*122"),
                    new Abilities("384*Hyper / Wallop*W*38"),
                    new Abilities("385*Icathian Rain*Q*53"),
                    new Abilities("386*Icathian Surprise*P*65"),
                    new Abilities("387*Ice Shard*Q*71"),
                    new Abilities("388*Iceborn Subjugation*P*71"),
                    new Abilities("389*Illumination*P*74"),
                    new Abilities("390*Impale*R*121"),
                    new Abilities("391*Incinerate*W*8"),
                    new Abilities("392*Indestructible*W*81"),
                    new Abilities("393*Infected Bonesaw*Q*26"),
                    new Abilities("394*Infernal Chains*W*1"),
                    new Abilities("395*Inferno Trigger*R*110"),
                    new Abilities("396*Infernum, the Flamethrower*P*9"),
                    new Abilities("397*Infinite Duress*R*150"),
                    new Abilities("398*Inherent Glamour*P*87"),
                    new Abilities("399*Inner Flame*Q*55"),
                    new Abilities("400*Insanity Potion*R*118"),
                    new Abilities("401*Inspire*E*55"),
                    new Abilities("402*Ionian Fervor*P*45"),
                    new Abilities("403*Iron Ambassador*P*96"),
                    new Abilities("404*Iron Mantle*W*138"),
                    new Abilities("405*Jack in the Box*W*115"),
                    new Abilities("406*Javelin Toss / Breakdown*Q*88"),
                    new Abilities("407*Jaws of the Beast*Q*150"),
                    new Abilities("408*Jousting*E*64"),
                    new Abilities("409*Joy Unending*P*89"),
                    new Abilities("410*Jubilant Veil*W*89"),
                    new Abilities("411*Judgment*E*37"),
                    new Abilities("412*Junkyard Titan*P*108"),
                    new Abilities("413*Justice Punch*E*35"),
                    new Abilities("414*Keeper's Verdict*R*96"),
                    new Abilities("415*Ki Barrier*P*116"),
                    new Abilities("416*Ki Burst*W*107"),
                    new Abilities("417*Killer Instinct*R*53"),
                    new Abilities("418*King's Tribute*P*134"),
                    new Abilities("419*Kingslayer*W*125"),
                    new Abilities("420*Knuckle Down*Q*114"),
                    new Abilities("421*Lamb's Respite*R*63"),
                    new Abilities("422*Last Breath*R*155"),
                    new Abilities("423*Last Caress*R*30"),
                    new Abilities("424*Last Embrace*W*112"),
                    new Abilities("425*Last Rites*Q*157"),
                    new Abilities("426*Lay Waste*Q*56"),
                    new Abilities("427*League of Draven*P*27"),
                    new Abilities("428*Leap*E*62"),
                    new Abilities("429*Leap of Faith*R*44"),
                    new Abilities("430*Leap Strike*Q*49"),
                    new Abilities("431*Let's Bounce!*R*159"),
                    new Abilities("432*Leverage*P*104"),
                    new Abilities("433*Life Form Disintegration Ray*R*143"),
                    new Abilities("434*Light Binding*Q*74"),
                    new Abilities("435*Lightning Crash*R*161"),
                    new Abilities("436*Lightning Field / Hyper Charge*W*50"),
                    new Abilities("437*Lightning Rush*E*61"),
                    new Abilities("438*Lightslinger*P*72"),
                    new Abilities("439*Lilting Lullaby*R*70"),
                    new Abilities("440*Living Artillery*R*65"),
                    new Abilities("441*Living Battery*P*161"),
                    new Abilities("442*Living Forge*P*94"),
                    new Abilities("443*Living Shadow*W*160"),
                    new Abilities("444*Living Vengeance*P*140"),
                    new Abilities("445*Loaded Dice*P*136"),
                    new Abilities("446*Looming Darkness*E*144"),
                    new Abilities("447*Love Tap*P*80"),
                    new Abilities("448*Lover's Leap*P*100"),
                    new Abilities("449*Loyalty Program*E*104"),
                    new Abilities("450*Lucent Singularity*E*74"),
                    new Abilities("451*Lunar Rush*E*25"),
                    new Abilities("452*Lunge*Q*33"),
                    new Abilities("453*Magical Journey*E*13"),
                    new Abilities("454*Magnet Storm*R*103"),
                    new Abilities("455*Make It Rain*E*80"),
                    new Abilities("456*Malefic Visions*E*76"),
                    new Abilities("457*Mana Barrier*P*15"),
                    new Abilities("458*Mana Surge*P*153"),
                    new Abilities("459*Mantra*R*55"),
                    new Abilities("460*Mark of the Kindred*P*63"),
                    new Abilities("461*Mark of the Storm*P*61"),
                    new Abilities("462*Martial Cadence*P*48"),
                    new Abilities("463*Martial Poise*P*54"),
                    new Abilities("464*Master At Arms*R*49"),
                    new Abilities("465*Maximum Dosage*R*26"),
                    new Abilities("466*Meditate*W*78"),
                    new Abilities("467*Mega Adhesive*W*118"),
                    new Abilities("468*Mega Inferno Bomb*R*162"),
                    new Abilities("469*Mercury Cannon / Mercury Hammer*R*50"),
                    new Abilities("470*Miasma*W*21"),
                    new Abilities("471*Mimic*R*67"),
                    new Abilities("472*Mirror Image*P*67"),
                    new Abilities("473*Missile Barrage*R*23"),
                    new Abilities("474*Mistral Bolt*Q*144"),
                    new Abilities("475*Mocking Shout*W*135"),
                    new Abilities("476*Molten Shield*E*8"),
                    new Abilities("477*Monsoon*R*47"),
                    new Abilities("478*Moonfall*R*25"),
                    new Abilities("479*Moonlight Vigil*R*9"),
                    new Abilities("480*Moonsilver Blade*P*25"),
                    new Abilities("481*More Sparkles!*P*164"),
                    new Abilities("482*Mortal Steel*Q*156"),
                    new Abilities("483*Mortal Will*P*95"),
                    new Abilities("484*Mounting Dread*E*63"),
                    new Abilities("485*Mourning Mist*E*157"),
                    new Abilities("486*Move Quick*W*131"),
                    new Abilities("487*Mystic Shot*Q*31"),
                    new Abilities("488*Nature's Grasp*R*77"),
                    new Abilities("489*Needlework*R*41"),
                    new Abilities("490*Nether Blade*W*57"),
                    new Abilities("491*Nether Grasp*R*76"),
                    new Abilities("492*Neurotoxin / Venomous Bite*Q*29"),
                    new Abilities("493*Nevermore*E*124"),
                    new Abilities("494*New Destiny*P*40"),
                    new Abilities("495*Night Hunter*P*141"),
                    new Abilities("496*Nimble Fighter*P*34"),
                    new Abilities("497*Nimbus Strike*E*151"),
                    new Abilities("498*Noxian Diplomacy*Q*129"),
                    new Abilities("499*Noxian Guillotine*R*24"),
                    new Abilities("500*Noxian Might*P*24"),
                    new Abilities("501*Noxious Blast*Q*21"),
                    new Abilities("502*Noxious Slipstream*P*118"),
                    new Abilities("503*Noxious Trap*R*131"),
                    new Abilities("504*Ntofo Strikes*Q*66"),
                    new Abilities("505*Null Sphere*Q*57"),
                    new Abilities("506*Obliterate*Q*81"),
                    new Abilities("507*On the Hunt*R*120"),
                    new Abilities("508*Onslaught*Q*9"),
                    new Abilities("509*Onslaught of Shadows*R*42"),
                    new Abilities("510*Orb of Deception*Q*2"),
                    new Abilities("511*Organic Destruction*P*143"),
                    new Abilities("512*Overdrive*W*15"),
                    new Abilities("513*Overload*Q*109"),
                    new Abilities("514*Paddle Star*Q*164"),
                    new Abilities("515*Pale Cascade*W*25"),
                    new Abilities("516*Parallel Convergence*W*28"),
                    new Abilities("517*Paranoia*R*90"),
                    new Abilities("518*Parrley*Q*36"),
                    new Abilities("519*Path Maker*W*66"),
                    new Abilities("520*Perfect Execution*R*3"),
                    new Abilities("521*Permafrost*E*111"),
                    new Abilities("522*Perseverance*P*37"),
                    new Abilities("523*Personal Space*W*144"),
                    new Abilities("524*Petricite Burst*P*125"),
                    new Abilities("525*Petrifying Gaze*R*21"),
                    new Abilities("526*Phantom Undertow*E*97"),
                    new Abilities("527*Phase*W*9"),
                    new Abilities("528*Phase Dive*E*28"),
                    new Abilities("529*Phenomenal Evil Power*P*142"),
                    new Abilities("530*Phosphorus Bomb*Q*23"),
                    new Abilities("531*Pick A Card*W*136"),
                    new Abilities("532*Pierce*Q*54"),
                    new Abilities("533*Piercing Arrow*Q*140"),
                    new Abilities("534*Piercing Darkness*Q*112"),
                    new Abilities("535*Piercing Light*Q*72"),
                    new Abilities("536*Pillar of Flame*W*16"),
                    new Abilities("537*Pillar of Ice*E*134"),
                    new Abilities("538*Piltover Peacemaker*Q*19"),
                    new Abilities("539*Pit Grit*P*114"),
                    new Abilities("540*Pix, Faerie Companion*P*73"),
                    new Abilities("541*Plasma Fission*Q*143"),
                    new Abilities("542*Playful / Trickster*E*34"),
                    new Abilities("543*Pocket Pistol*Q*64"),
                    new Abilities("544*Poison Trail*Q*118"),
                    new Abilities("545*Pop Blossom*R*87"),
                    new Abilities("546*Portal Jump*R*164"),
                    new Abilities("547*Pow-Pow, the Minigun*Q*52"),
                    new Abilities("548*Powder Keg*E*36"),
                    new Abilities("549*Power Chord*P*122"),
                    new Abilities("550*Power Fist*E*15"),
                    new Abilities("551*Powerball*Q*101"),
                    new Abilities("552*Precision Protocol*Q*20"),
                    new Abilities("553*Preparation*W*58"),
                    new Abilities("554*Primal Howl*E*150"),
                    new Abilities("555*Primal Surge / Swipe*E*88"),
                    new Abilities("556*Primordial Burst*R*142"),
                    new Abilities("557*Prismatic Barrier*W*74"),
                    new Abilities("558*Prophet of an Elder God*P*44"),
                    new Abilities("559*Prowl*P*88"),
                    new Abilities("560*Prowling Projectile*Q*158"),
                    new Abilities("561*Pulverize*Q*5"),
                    new Abilities("562*Purge*W*139"),
                    new Abilities("563*Pyroclasm*R*16"),
                    new Abilities("564*Pyromania*P*8"),
                    new Abilities("565*Queen's Wrath / Prey Seeker*Q*102"),
                    new Abilities("566*Quickdraw*E*40"),
                    new Abilities("567*Radiant Blast*Q*59"),
                    new Abilities("568*Rage Gene*P*38"),
                    new Abilities("569*Ragnarok*R*92"),
                    new Abilities("570*Rake*W*129"),
                    new Abilities("571*Rampage*Q*42"),
                    new Abilities("572*Rampant Growth*W*165"),
                    new Abilities("573*Ranger's Focus*Q*10"),
                    new Abilities("574*Rapid Fire*Q*133"),
                    new Abilities("575*Rappel*E*29"),
                    new Abilities("576*Ravenous Flock*P*124"),
                    new Abilities("577*Razor Shuriken*Q*160"),
                    new Abilities("578*Realm of Death*R*81"),
                    new Abilities("579*Realm Warp*R*109"),
                    new Abilities("580*Reap*E*32"),
                    new Abilities("581*Reaping Slash*Q*60"),
                    new Abilities("582*Rebirth*P*7"),
                    new Abilities("583*Reckless Swing*E*92"),
                    new Abilities("584*Reign of Anger*P*105"),
                    new Abilities("585*Relentless Assault*P*49"),
                    new Abilities("586*Relentless Force*E*145"),
                    new Abilities("587*Relentless Pursuit*E*72"),
                    new Abilities("588*Remove Scurvy*W*36"),
                    new Abilities("589*Rend*E*54*"),
                    new Abilities("590*Renewal*W*55"),
                    new Abilities("591*Requiem*R*56"),
                    new Abilities("592*Rewind*W*163"),
                    new Abilities("593*Ricochet*W*120"),
                    new Abilities("594*Riftwalk*R*57"),
                    new Abilities("595*Ring of Frost*W*71"),
                    new Abilities("596*Riposte*W*33"),
                    new Abilities("597*Riptide*E*86"),
                    new Abilities("598*Rising Spell Force*P*31"),
                    new Abilities("599*Rite of the Arcane*R*153"),
                    new Abilities("600*Roar of the Slayer*E*119"),
                    new Abilities("601*Rock Surfing*P*128"),
                    new Abilities("602*Rocket Grab*Q*15"),
                    new Abilities("603*Rocket Jump*W*133"),
                    new Abilities("604*Rootcaller*Q*46"),
                    new Abilities("605*Royal Maelstrom*E*14"),
                    new Abilities("606*Royal Privilege*P*98"),
                    new Abilities("607*Rune Prison*W*109"),
                    new Abilities("608*Runic Blade*P*107"),
                    new Abilities("609*Rupture*Q*22"),
                    new Abilities("610*Ruthless Predator*W*105"),
                    new Abilities("611*Safeguard / Iron Will*W*68"),
                    new Abilities("612*Salvation*P*123"),
                    new Abilities("613*Sanguine Pool*W*148"),
                    new Abilities("614*Sap Magic*P*77"),
                    new Abilities("615*Sapling Toss*E*77"),
                    new Abilities("616*Satchel Charge*W*162"),
                    new Abilities("617*Savagery*Q*106"),
                    new Abilities("618*Scatter the Weak*E*126"),
                    new Abilities("619*Scrap Shield*W*108"),
                    new Abilities("620*Sear*Q*16"),
                    new Abilities("621*Searing Charge*E*94"),
                    new Abilities("622*Seastone Trident*W*34"),
                    new Abilities("623*Second Skin*P*53"),
                    new Abilities("624*Seismic Shard*Q*75"),
                    new Abilities("625*Seismic Shove*W*128"),
                    new Abilities("626*Sentinel*W*54"),
                    new Abilities("627*Sentry*Q*9"),
                    new Abilities("628*Serpentine Grace*P*21"),
                    new Abilities("629*Severum, the Scythe Pistol*P*9"),
                    new Abilities("630*Shadow Assault*R*129"),
                    new Abilities("631*Shadow Dash*E*116"),
                    new Abilities("632*Shadow Slash*E*160"),
                    new Abilities("633*Shadow Step*E*60"),
                    new Abilities("634*Shadow Surge*R*144"),
                    new Abilities("635*Shapesplitter*W*87"),
                    new Abilities("636*Shattering Strike*Q*103"),
                    new Abilities("637*Shepherd of Souls*P*157"),
                    new Abilities("638*Shield of Daybreak*Q*69"),
                    new Abilities("639*Shield of Durand*W*35"),
                    new Abilities("640*Shield Vault*W*95"),
                    new Abilities("641*Shifting Sands*E*12"),
                    new Abilities("642*Shocking Orb*E*153"),
                    new Abilities("643*Short Fuse*P*162"),
                    new Abilities("644*Shroud of Darkness*W*90"),
                    new Abilities("645*Shunpo*E*58"),
                    new Abilities("646*Shuriken Flip*E*3"),
                    new Abilities("647*Shurima's Legacy*P*12"),
                    new Abilities("648*Sigil of Malice*Q*67"),
                    new Abilities("649*Silver Bolts*W*141"),
                    new Abilities("650*Singularity*E*11"),
                    new Abilities("651*Siphon Power*Q*147"),
                    new Abilities("652*Siphoning Strike*Q*85"),
                    new Abilities("653*Skaarl the Cowardly Lizard*P*64"),
                    new Abilities("654*Skip 'n Slash*E*41"),
                    new Abilities("655*Sky Splitter*E*149"),
                    new Abilities("656*Skystrike*R*99"),
                    new Abilities("657*Sleepy Trouble Bubble*E*164"),
                    new Abilities("658*Slice and Dice*E*105"),
                    new Abilities("659*Slicing Maelstrom*R*61"),
                    new Abilities("660*Slipstream*E*89"),
                    new Abilities("661*Smoke Screen*W*40"),
                    new Abilities("662*Snip Snip!*Q*41"),
                    new Abilities("663*Snowball Barrage*E*91"),
                    new Abilities("664*Soaring Slam*R*101"),
                    new Abilities("665*Solar Flare*R*69"),
                    new Abilities("666*Song of Celerity*E*122"),
                    new Abilities("667*Sonic Wave / Resonating Strike*Q*68"),
                    new Abilities("668*Soul Eater*P*85"),
                    new Abilities("669*Soul Furnace*W*119"),
                    new Abilities("670*Soul Shackles*R*82"),
                    new Abilities("671*Soul Siphon*P*82"),
                    new Abilities("672*Soul Unbound*E*156"),
                    new Abilities("673*Soulflare*Q*55"),
                    new Abilities("674*Sovereign's Domination*P*146"),
                    new Abilities("675*Spark Surge*E*161"),
                    new Abilities("676*Spectral Maw*W*146"),
                    new Abilities("677*Spell Flux*E*109"),
                    new Abilities("678*Spell Shield*E*120"),
                    new Abilities("679*Spell Thief*W*164"),
                    new Abilities("680*Spider Queen*P*29"),
                    new Abilities("681*Spiked Shell*P*101"),
                    new Abilities("682*Spinning Axe*Q*27"),
                    new Abilities("683*Spinning Slash*E*135"),
                    new Abilities("684*Spirit Cleave*W*156"),
                    new Abilities("685*Spirit Fire*E*85"),
                    new Abilities("686*Spirit of Dread*W*42"),
                    new Abilities("687*Spitit Rush*R*2"),
                    new Abilities("688*Spirit's Refuge*W*116"),
                    new Abilities("689*Spray and Pray*R*137"),
                    new Abilities("690*Stacked Deck*E*136"),
                    new Abilities("691*Stage Presence*P*113"),
                    new Abilities("692*Staggering Blow*P*86"),
                    new Abilities("693*Stand Aside*E*27"),
                    new Abilities("694*Stand Behind Me*W*17"),
                    new Abilities("695*Stand United*R*116"),
                    new Abilities("696*Starcall*Q*123"),
                    new Abilities("697*Starfire Spellblade*E*59"),
                    new Abilities("698*Starlight's Touch*Q*130"),
                    new Abilities("699*Static Field*R*15"),
                    new Abilities("700*Steadfast Presence*W*96"),
                    new Abilities("701*Steel Tempest*Q*155"),
                    new Abilities("702*Stone Skin*P*151"),
                    new Abilities("703*Stormbringer*R*149"),
                    new Abilities("704*Stranglethorns*R*165"),
                    new Abilities("705*Stretching Strikes*Q*159"),
                    new Abilities("706*Strut*W*80"),
                    new Abilities("707*Subjugate*R*134"),
                    new Abilities("708*Summon: Tibbers*R*8"),
                    new Abilities("709*Sunlight*P*69"),
                    new Abilities("710*Super Mega Death Rocket!*R*52"),
                    new Abilities("711*Supercharge*E*53"),
                    new Abilities("712*Supreme Display of Talent*R*98"),
                    new Abilities("713*Surging Tides*P*84"),
                    new Abilities("714*Surround Sound*W*113"),
                    new Abilities("715*Sweeping Blade*E*155"),
                    new Abilities("716*Swipe*E*88"),
                    new Abilities("717*Swirlseed*E*70"),
                    new Abilities("718*Switcheroo!*Q*52"),
                    new Abilities("719*Tactical Sweep*W*20"),
                    new Abilities("720*Tailwind*P*47"),
                    new Abilities("721*Takedown*Q*88"),
                    new Abilities("722*Tangle-Barbs*E*87"),
                    new Abilities("723*Tantrum*E*6"),
                    new Abilities("724*Taste Their Fear*Q*62"),
                    new Abilities("725*Testonic Disruption*E*143"),
                    new Abilities("726*Tempered Fate*R*13"),
                    new Abilities("727*Tempest*E*68"),
                    new Abilities("728*Tentacle Smash*Q*44"),
                    new Abilities("729*Terrashape*E*98"),
                    new Abilities("730*Terrify*Q*32"),
                    new Abilities("731*Test of Spirit*E*44"),
                    new Abilities("732*The Box*R*132"),
                    new Abilities("733*The Call of the Pack*R*83"),
                    new Abilities("734*The Culling*R*72"),
                    new Abilities("735*The Darkin Blade*Q*1"),
                    new Abilities("736*The Darkin Scythe*P*60"),
                    new Abilities("737*The Equalizer*R*108"),
                    new Abilities("738*The Hitman and the Seer*P*9"),
                    new Abilities("739*The Quickness*R*100"),
                    new Abilities("740*The Relentless Storm*P*149"),
                    new Abilities("741*The Show Stopper*R*114"),
                    new Abilities("742*Thick Skin*E*127"),
                    new Abilities("743*Thousand Cuts*P*41"),
                    new Abilities("744*Threaded Volley*Q*128"),
                    new Abilities("745*Three Talon Strike*Q*154"),
                    new Abilities("746*Thrill of the Hunt*R*106"),
                    new Abilities("747*Thunderclap*W*75"),
                    new Abilities("748*Thundering Blow / Acceleration Gate*E*50"),
                    new Abilities("749*Thundering Shuriken*Q*61"),
                    new Abilities("750*Thundering Smash*Q*149"),
                    new Abilities("751*Tidal Wave*R*84"),
                    new Abilities("752*Tidecaller's Blessing*E*84"),
                    new Abilities("753*Tides of Blood*E*148"),
                    new Abilities("754*Time Bomb*Q*163"),
                    new Abilities("755*Time in a Bottle*P*163"),
                    new Abilities("756*Time Warp*E*163"),
                    new Abilities("757*Timewinder*Q*28"),
                    new Abilities("758*Titan's Wrath*W*86"),
                    new Abilities("759*To The Skies! / Shock Blast*Q*50"),
                    new Abilities("760*Tongue Lash*Q*127"),
                    new Abilities("761*Tormented Shadow*W*82"),
                    new Abilities("762*Tough It Out*W*92"),
                    new Abilities("763*Toxic Shot*E*131"),
                    new Abilities("764*Trample*E*5"),
                    new Abilities("765*Transcendent*P*126"),
                    new Abilities("766*Transfusion*Q*148"),
                    new Abilities("767*Traveler's Call*P*13"),
                    new Abilities("768*Trial By Fire*P*36"),
                    new Abilities("769*Triggerseed*E*46"),
                    new Abilities("770*Triumphant Roar*P*5"),
                    new Abilities("771*Trueshot Barrage*R*31"),
                    new Abilities("772*Tumble*Q*141"),
                    new Abilities("773*Twilight Assault*Q*116"),
                    new Abilities("774*Twilight Shroud*W*3"),
                    new Abilities("775*Twin Bite*Q*117"),
                    new Abilities("776*Twin Fang*E*21"),
                    new Abilities("777*Twisted Advance*W*77"),
                    new Abilities("778*Two-Shiv Prison*E*115"),
                    new Abilities("779*Ultra Mega Fire Kick*Q*79"),
                    new Abilities("780*Ultrashock Laser*W*161"),
                    new Abilities("781*Umbra Blades*P*90"),
                    new Abilities("782*Umbral Dash*E*1"),
                    new Abilities("783*Umbral Trespass*R*60"),
                    new Abilities("784*Unbreakable*E*17"),
                    new Abilities("785*Unbreakable Will*R*5"),
                    new Abilities("786*Undertow*Q*92"),
                    new Abilities("787*Undying Rage*R*135"),
                    new Abilities("788*Unleashed Power*R*126"),
                    new Abilities("789*Unraveled Earth*E*128"),
                    new Abilities("790*Unseen Predator*P*106"),
                    new Abilities("791*Unseen Threat*P*62"),
                    new Abilities("792*Unspeakable Horror*E*90"),
                    new Abilities("793*Unstable Matter*W*159"),
                    new Abilities("794*Unstoppable Force*R*75"),
                    new Abilities("795*Unstoppable Onslaught*R*119"),
                    new Abilities("796*UPGRADE!!!*R*43"),
                    new Abilities("797*Urchin Strike*Q*34"),
                    new Abilities("798*Valkyrie*W*23"),
                    new Abilities("799*Valor*E*107"),
                    new Abilities("800*Vanguard's Edge*R*45"),
                    new Abilities("801*Vault*E*99"),
                    new Abilities("802*Vault Breaker*Q*145"),
                    new Abilities("803*Venom Cask*W*137"),
                    new Abilities("804*Violent Tendencies*W*64"),
                    new Abilities("805*Vision of Empire*W*124"),
                    new Abilities("806*Void Assault*R*62"),
                    new Abilities("807*Void Ooze*E*65"),
                    new Abilities("808*Void Rift*W*143"),
                    new Abilities("809*Void Rush*R*102"),
                    new Abilities("810*Void Seeker*W*53"),
                    new Abilities("811*Void Shift*P*76"),
                    new Abilities("812*Void Spike*W*62"),
                    new Abilities("813*Void Stone*P*57"),
                    new Abilities("814*Void Surge*Q*14"),
                    new Abilities("815*Void Swarm*W*76"),
                    new Abilities("816*Volatile Spiderling / Skittering Frenzy*W*29"),
                    new Abilities("817*Volcanic Rupture*Q*94"),
                    new Abilities("818*Volley*W*10"),
                    new Abilities("819*Voracity*P*58"),
                    new Abilities("820*Vorpal Spikes*E*22"),
                    new Abilities("821*Wall Dive*E*20"),
                    new Abilities("822*Wall of Pain*W*56"),
                    new Abilities("823*Warm Hugs*E*79"),
                    new Abilities("824*Warpath*P*42"),
                    new Abilities("825*Warrior Trickster*W*151"),
                    new Abilities("826*Watch Out! Eep!*W*70"),
                    new Abilities("827*Way of the Hunter*P*156"),
                    new Abilities("828*Way of the Wanderer*P*155"),
                    new Abilities("829*We Are More*P*83"),
                    new Abilities("830*Weaver's Wall*R*128"),
                    new Abilities("831*Whimsy*W*73"),
                    new Abilities("832*Whiplash*E*30"),
                    new Abilities("833*Whirling Death*R*27"),
                    new Abilities("834*Whisper*P*51"),
                    new Abilities("835*Wild Cards*Q*136"),
                    new Abilities("836*Wild Growth*R*73"),
                    new Abilities("837*Wild Rush*E*110"),
                    new Abilities("838*Wilding Claw*Q*138"),
                    new Abilities("839*Wind Becomes Lightning*W*154"),
                    new Abilities("840*Wind Slash*R*107"),
                    new Abilities("841*Wind Wall*W*155"),
                    new Abilities("842*Winds of War*Q*35"),
                    new Abilities("843*Wingborne Storm*R*138"),
                    new Abilities("844*Winter's Bite*Q*17"),
                    new Abilities("845*Winter's Wrath*W*111"),
                    new Abilities("846*Wish*R*123"),
                    new Abilities("847*Wither*W*85"),
                    new Abilities("848*Wolf's Frenzy*W*63"),
                    new Abilities("849*World Ender*R*1"),
                    new Abilities("850*Wuju Style*E*78"),
                    new Abilities("851*Yordle Snap Trap*W*19"),
                    new Abilities("852*You and Me!*W*158"),
                    new Abilities("853*Z-Drive Resonance*P*28"),
                    new Abilities("854*Zap!*W*52"),
                    new Abilities("855*Zenith Blade*E*69"),
                    new Abilities("856*Zephyr*W*47"),
                    new Abilities("857*Zoomies*E*158"),                    
                });
        }
    }
}
